import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  output: "standalone",
  turbopack: {
    root: ".",
  },
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "**.unsplash.com" },
      { protocol: "https", hostname: "images.unsplash.com" },
      { protocol: "https", hostname: "plus.unsplash.com" },
      { protocol: "https", hostname: "**.samsung.com" },
      { protocol: "https", hostname: "image-us.samsung.com" },
      { protocol: "https", hostname: "images.samsung.com" },
      { protocol: "https", hostname: "**.lge.co.kr" },
      { protocol: "https", hostname: "www.lg.com" },
      { protocol: "https", hostname: "media.us.lg.com" },
      { protocol: "https", hostname: "**.apple.com" },
      { protocol: "https", hostname: "www.apple.com" },
      { protocol: "https", hostname: "store.storeimages.cdn-apple.com" },
      { protocol: "https", hostname: "assets.breville.com" },
      { protocol: "https", hostname: "assets.bosecreative.com" },
      { protocol: "https", hostname: "images.ctfassets.net" },
      { protocol: "https", hostname: "i01.appmifile.com" },
      { protocol: "https", hostname: "site-static.ecovacs.com" },
      { protocol: "https", hostname: "images.philips.com" },
      { protocol: "https", hostname: "dam.delonghi.com" },
      { protocol: "https", hostname: "www.vitamix.com" },
      { protocol: "https", hostname: "balmudtr0795.cdn-nhncommerce.com" },
      { protocol: "https", hostname: "assets.nintendo.com" },
      { protocol: "https", hostname: "gmedia.playstation.com" },
      { protocol: "https", hostname: "cdn-dynmedia-1.microsoft.com" },
      { protocol: "https", hostname: "m-cdn.phonearena.com" },
      { protocol: "https", hostname: "i02.appmifile.com" },
      { protocol: "https", hostname: "www.elago.com" },
      { protocol: "https", hostname: "kr.object.ncloudstorage.com" },
      { protocol: "https", hostname: "morningmagickeurig.com" },
      { protocol: "https", hostname: "www.casscale.com.au" },
      { protocol: "https", hostname: "shop.panasonic.com" },
      { protocol: "https", hostname: "crawl-cdn.nosearch.com" },
      { protocol: "https", hostname: "www.audio-technica.com" },
      { protocol: "https", hostname: "us.sennheiser-hearing.com" },
      { protocol: "https", hostname: "www.irobot.com" },
      { protocol: "https", hostname: "instantpot.com" },
      { protocol: "https", hostname: "newworld.co.za" },
      { protocol: "https", hostname: "www.electricshop.com" },
      { protocol: "https", hostname: "images.icecat.biz" },
      { protocol: "https", hostname: "dyson-h.assetsadobe2.com" },
      { protocol: "https", hostname: "pisces.bbystatic.com" },
      { protocol: "https", hostname: "ns-curation.s3.ap-northeast-2.amazonaws.com" },
      { protocol: "https", hostname: "ca.jbl.com" },
    ],
  },
};

export default nextConfig;
